input {
  file {
    path => "/usr/share/logstash/ingest_data/application.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}
filter {
  if [message] =~ "STATISTIC-LOG" {
    grok {
      match => {
        "message" => "%{LOGLEVEL:level} %{DATA:class} : STATISTIC-LOG %{DATA:method} -> Malware: %{DATA:malware_name}, Analyst: %{DATA:analyst_name}, Location: %{GREEDYDATA:location_name}"
      }
    }
  } else {
    drop { }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "statistic-data-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
