spring.application.name=udd-project
server.port=8080

# DATABASE (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/udd_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ELASTICSEARCH
spring.elasticsearch.uris=http://localhost:9200
elasticsearch.host=localhost
elasticsearch.port=9200
elasticsearch.username=
elasticsearch.password=

# MINIO
spring.minio.url=http://localhost:9000
spring.minio.bucket=udd-reports
spring.minio.access-key=minioadmin
spring.minio.secret-key=minioadmin

# FILE UPLOAD LIMITS
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# LOGGING CONFIGURATION
logging.file.name=logs/application.log
logging.pattern.file=%level %logger{10} : %msg%n
logging.pattern.console=%d{HH:mm:ss} %-5level %logger{36} - %msg%n

# LocationIQ API Key
location.iq.api.key=pk.d18d82409e3711cdabef27421eee9fb4

app.jwt.secret=OvoJeNekiVeomaDugacakTajniKljucZaPotpisivanjeTokena99999
app.jwt.expiration-ms=86400000  
